# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostedProbady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('ctime', models.IntegerField(default=1504848240.7049005)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('clickNum', models.IntegerField(db_index=True)),
                ('voltNums', models.IntegerField()),
                ('belittleNums', models.IntegerField()),
                ('commentNums', models.IntegerField(db_index=True)),
                ('classify', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostedReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postedId', models.IntegerField()),
                ('uId', models.IntegerField()),
                ('replyId', models.IntegerField(default=0)),
                ('voltNums', models.IntegerField()),
                ('belittleNums', models.IntegerField()),
                ('ctime', models.IntegerField(default=1504848240.7059007)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TopClassifyEnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumName', models.CharField(max_length=50)),
                ('pid', models.IntegerField()),
                ('leveval', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('ctime', models.IntegerField(default=1504848240.7059007)),
                ('lastSiginTime', models.IntegerField(default=1504848240.7059007)),
                ('allowLog', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('picture', models.CharField(default='default/default_mugshot.png', max_length=50)),
                ('signature', models.CharField(max_length=50)),
            ],
        ),
    ]
