# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topclassifyenum',
            old_name='leveval',
            new_name='level',
        ),
        migrations.AlterField(
            model_name='postedprobady',
            name='ctime',
            field=models.IntegerField(default=1504850143.0177066),
        ),
        migrations.AlterField(
            model_name='postedreply',
            name='ctime',
            field=models.IntegerField(default=1504850143.0187068),
        ),
        migrations.AlterField(
            model_name='user',
            name='ctime',
            field=models.IntegerField(default=1504850143.0187068),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastSiginTime',
            field=models.IntegerField(default=1504850143.0187068),
        ),
    ]
